### ISSUE TITLE
Adding a link to the CS+ PhD student manuals on wiki

### ISSUE THREAD

**Issue by nick-lagrassa** [nu-cspac/nu-cs#3]
Hi, CSPAC!

Could you please add a link in the wiki for each of the CS-affiliated PhD manuals? Below are the links for each of the programs programs.

CS: https://www.mccormick.northwestern.edu/computer-science/documents/2021-20.cs.gradstudymanual_v271.pdf
CSLS: https://csls.sesp.northwestern.edu/res/handbook.pdf
TSB: https://media.soc.northwestern.edu/socwp-aws/sites/48/2020/10/04114310/TSB-Handbook-2020-2021.pdf
CE: https://www.mccormick.northwestern.edu/computer-science/academics/graduate/ce-graduate-manual.pdf

Thanks,
Nick

P.S. Thanks for maintaining the resources on the CSPAC wiki. I'm in my 3rd year and I still find these resources helpful.

**Comment by cspac-nu** [comment]
The manuals have been added. Thanks for the feedback!
